linters:
  enable:
    - errname
    - errcheck
    - gocheckcompilerdirectives
    - gocyclo
    - lll
    - makezero
    - godot
    - unparam
    - unused

linters-settings:
  gocyclo:
    min-complexity: 15
  lll:
    tab-width: 4
    line-length: 79
