#!/bin/sh

set -e

run clean
run ci

export CGO_ENABLED=0

while IFS=':' read -r GOOS GOARCH
do
    echo "Building $GOOS/$GOARCH"
    export GOOS GOARCH
    go build -ldflags="-s -w" -o /dev/null
done < etc/platforms
