name: main
on: [push]
jobs:
  op:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          check-latest: true
      - run: go install lesiw.io/op@latest
      - run: op
